### PR TITLE
Prevent accidental reconfiguration of running server

### LINKED ISSUE #157: Throw exception, when options are changed on running server
The `Behat\Mink\Driver\NodeJS\Server` class have bunch of methods for setting options of the NodeJS server, that will be created. There is only one problem with them: when used on already running server they:

* have no effect
* developer thinks all worked fine

Proposing to throw an exception, when attempt to change running server options is made.

### PR DESCRIPTION
**Pull request by aik099**
Closes #157

### CODE REVIEW

File: src/NodeJS/Server.php [hunk 1]
```diff
@@ -109,9 +109,15 @@ public function __destruct()
      * Setter host
      *
      * @param string $host The server host
+     *
+     * @throws \RuntimeException When server is already running.
      */
     public function setHost($host)
     {
+        if ($this->isRunning()) {
+            throw new \RuntimeException('Unable to change host of a running server.');
```
Comment (stof) [inline src/NodeJS/Server.php]: I think a ``LogicException`` would make more sense (it is an error in the logic of your program if you try to do it)

Comment (aik099) [inline src/NodeJS/Server.php]: Done.
