### PR TITLE
Fixes header retrieval for Zombie 4.x+ versions

### LINKED ISSUE #134: Change way of retrieving headers from Zombie 4.x
In Zombie 4.x header retrieval should be done differently, because now `headers` property of `browser._response` isn't an array, but an object of `Fetch` class having `_headers` property (see https://github.com/assaf/zombie/blob/master/src/fetch.js#L25). I bet there is a getter method, that can be used.

We need however to place zombie version check around new code to keep header retrieval working for older Zombie versions.

Output of PHPUnit:

```
PHPUnit 4.6.10 by Sebastian Bergmann and contributors.

Configuration read from .../phpunit.xml

...............................................................  63 / 166 ( 37%)
...FS...S......SSSSS...............SSSS...............S........ 126 / 166 ( 75%)
.................S...............S..SSS

Time: 19.64 seconds, Memory: 12.50Mb

There was 1 failure:

1) Behat\Mink\Tests\Driver\Basic\HeaderTest::testResponseHeaders
Failed asserting that an array has the key 'x-mink-test'.

.../vendor/behat/mink/driver-testsuite/tests/Basic/HeaderTest.php:75

FAILURES!
Tests: 163, Assertions: 394, Failures: 1, Skipped: 17.
```

### PR DESCRIPTION
**Pull request by aik099**
Closes #134

### CODE REVIEW

**Comment by stof** [comment]
hmm, why the hell is ``npm install zombie`` giving us the 4.x version on node when they are not compatible.

We need to set ``ZOMBIE_VERSION='^3.0'`` by default in builds.

File: src/ZombieDriver.php [hunk 1]
```diff
@@ -236,7 +236,16 @@ public function setRequestHeader($name, $value)
      */
     public function getResponseHeaders()
     {
-        return (array) $this->server->evalJS('browser.window._response.headers', 'json');
+        $js = <<<JS
+        if (true == zombieVersionCompare('4.0.0', '>=')) {
+          stream.end(JSON.stringify(browser.window._response.headers.toObject()));
```
Comment (stof) [inline src/ZombieDriver.php]: the public API to access the response in Zombie 4 is ``browser.response``

File: src/ZombieDriver.php [hunk 2]
```diff
@@ -236,7 +236,16 @@ public function setRequestHeader($name, $value)
      */
     public function getResponseHeaders()
     {
-        return (array) $this->server->evalJS('browser.window._response.headers', 'json');
+        $js = <<<JS
+        if (true == zombieVersionCompare('4.0.0', '>=')) {
```
Comment (stof) [inline src/ZombieDriver.php]: could we rely on some feature detection rather than version sniffing ? this would be more consistent with our Zombie 2/3 support

Comment (aik099) [inline src/ZombieDriver.php]: > could we rely on some feature detection rather than version sniffing ?

Any example of that, that you can link to?

In this case the `headers` property always exists, but it's contents is different. Not sure what to check.

File: src/ZombieDriver.php (hunk 1 above)
Comment (aik099) [inline src/ZombieDriver.php]: > the public API to access the response in Zombie 4 is browser.response

Does it solve AJAX problem, when page does several AJAX requests once it's loaded and `browser.response` contains last AJAX request response instead of main page response? For that reason I was using `browser.window._response` instead of `browser.response` (maybe it existed in Zombie 2.x too).

Comment (stof) [inline src/ZombieDriver.php]: ``browser.response`` is just calling ``browser.window._response`` internally: https://github.com/assaf/zombie/blob/0382cf3442a62db4dea0cca563335137e3ad7083/src/index.js#L1154.
But it is a public API, which is better than accessing the internal ``_response`` property (and no, ``browser.response`` does not exist in 2.x or 3.x)

File: src/ZombieDriver.php (hunk 2 above)
Comment (stof) [inline src/ZombieDriver.php]: check whether the ``toObject`` method exists :)

File: src/ZombieDriver.php (hunk 1 above)
Comment (aik099) [inline src/ZombieDriver.php]: OK. Will fix that.

File: src/ZombieDriver.php (hunk 2 above)
Comment (aik099) [inline src/ZombieDriver.php]: I've just arrived from vacation yesterday so I'm not in working mood yet ;)

File: src/ZombieDriver.php (hunk 1 above)
Comment (aik099) [inline src/ZombieDriver.php]: Done, waiting for test results.

File: src/ZombieDriver.php [hunk 3]
```diff
@@ -236,7 +236,14 @@ public function setRequestHeader($name, $value)
      */
     public function getResponseHeaders()
     {
-        return (array) $this->server->evalJS('browser.window._response.headers', 'json');
+        $js = <<<JS
+var response = browser.response ? browser.response : browser.window._response,
```
Comment (stof) [inline src/ZombieDriver.php]: Write it the JS way:

```js
var response = browser.response || browser.window._response
```

Comment (aik099) [inline src/ZombieDriver.php]: Done.

**Comment by aik099** [comment]
Rebased so that we can have working IO.JS-based Zombie 4.0 build working to see if header retrieval really working.

**Comment by aik099** [comment]
Merging.
